package com.tonapps.brotherhood.config

object BrotherhoodErrors {
    val TVM_EXIT_CODES: Map<Int, String> = mapOf(
        // Standard TVM Exceptions
        0 to "Success",
        1 to "Alternative Success",
        2 to "Stack Underflow",
        3 to "Stack Overflow",
        4 to "Integer Overflow",
        5 to "Integer Out of Range",
        6 to "Invalid Opcode",
        7 to "Type Check Error",
        8 to "Cell Overflow",
        9 to "Cell Underflow",
        10 to "Dictionary Error",
        11 to "Unknown Error",
        13 to "Out of Gas",
        // Common Contract Errors
        47 to "Balance Error",
        48 to "Not Enough Gas",
        49 to "Invalid Message",
        70 to "Invalid Subdomain Bits",
        72 to "Invalid Op",
        73 to "Not Owner",
        74 to "Not Valid Wallet",
        204 to "Bid Below Minimum Price",
        250 to "Max Connections",
        333 to "Wrong Workchain",
        401 to "Not Domain Owner",
        402 to "Not Enough Domain Balance",
        404 to "Not Found",
        405 to "Not From Collection",
        406 to "Only Owner Can Fill Up After Auction",
        407 to "Bid Too Low",
        410 to "Only Owner Can Edit Content",
        411 to "Only Owner Can Change DNS",
        412 to "Invalid Content Tag",
        413 to "Governance Requires No Active Auction",
        414 to "DNS Balance Release Forbidden",
        420 to "No Active Auction",
        421 to "Auction Not Finished",
        422 to "Auction Already Finished",
        423 to "No Auction Winner",
        424 to "Incorrect Sender",
        // Brotherhood Specific Errors
        700 to "Incorrect Sender",
        701 to "Account Terminated",
        702 to "Account Inactive",
        703 to "Insufficient Gas Sent",
        704 to "Reserved Internal",
        705 to "Upgrade Wallet",
        706 to "No Pending Request",
        707 to "Cannot Unfollow Reported",
        708 to "Incorrect Receiver",
        709 to "Insufficient Balance",
        710 to "Already Reported",
        711 to "Account Not Reported",
        719 to "Connection Exists",
        720 to "Not Friend",
        721 to "Not Invitor",
        723 to "Already Invited",
        724 to "Unauthorized Burn",
        730 to "Mint Closed",
        731 to "No Votes Available",
        732 to "Not Voted Yet",
        733 to "Upgrade Required",
        734 to "Version Mismatch",
        735 to "Wait More",
        736 to "Not Close Friend",
        737 to "Already Vouched",
        738 to "Provide Coordinates",
        739 to "Invalid Forward Payload",
        740 to "Invite First",
        741 to "Already Reported For Other Reason",
        750 to "Proposal Already Active",
        751 to "Proposal Not Found",
        752 to "Proposal Pending Accounts",
        753 to "Proposal Already Executed",
        754 to "Proposal Expired",
        755 to "Already Voted",
        756 to "Proposal Fee Insufficient",
        757 to "Duplicate Vote",
        758 to "Invalid DAO Voter",
        759 to "Country Mismatch",
        760 to "Credit Need Exceeded",
        761 to "Account In Debt",
        762 to "Has Active Votes",
        763 to "Credit Not Matured",
        764 to "Personal Jetton Not Registered",
        765 to "Deferred Payment Disabled",
        766 to "Wallet Not Onboarded",
        65535 to "Invalid Message Body",
    )

    fun decodeExitCode(code: Int): String {
        val label = TVM_EXIT_CODES[code]
        return if (label != null) {
            "$label (exit $code)"
        } else {
            "Exit $code"
        }
    }
}
